### ISSUE TITLE
Build issue when using qt5

### ISSUE THREAD

**Issue by texke** [nethershaw/gridcoin#5]
Hi,

as a follow-up to all the other topics here, I'm having build problems with USE flags "boinc dbus qt5 -daemon -qrcode -upnp"

/usr/lib64/qt5/bin/rcc -name bitcoin src/qt/bitcoin.qrc -o qrc_bitcoin.cpp
RCC: Error in 'src/qt/bitcoin.qrc': Cannot find file 'locale/bitcoin_ar.qm'
make: *** [Makefile:995: qrc_bitcoin.cpp] Error 1

To fix this, I had to install dev-qt/linguist-tools.
Should this package be included into the deps when using qt5?

**Comment by nethershaw** [comment]
Confirmed; it should. Thank you for the report. Pushing a fix shortly.
