### ISSUE TITLE
Gridcoin: Error initializing database environment

### ISSUE THREAD

**Issue by NuLL3rr0r** [nethershaw/gridcoin#6]
I forked your repository long ago and I kept updating it up to 3.7.11.0. I decided to switch back to your repository to get the latest version and the new changes. When I emerge gridcoin it emerges fine using the following use flags:

3.7.11.0

```
[ebuild   R    ] net-p2p/gridcoin-3.7.11.0-r3::gridcoin  USE="boinc daemon -dbus -qrcode -qt5 -upnp" 0 KiB
```

3.7.12.0

```
[ebuild   R    ] net-p2p/gridcoin-3.7.12.0::gridcoin  USE="boinc daemon harden -bench -ccache -dbus -debug -libraries -pic -qrcode -qt5 -static {-test} -upnp -utils" 0 KiB
```

3.7.13.0

```
[ebuild   R    ] net-p2p/gridcoin-3.7.13.0::gridcoin  USE="boinc daemon harden -bench -ccache -dbus -debug -libraries -pic -qrcode -qt5 -static {-test} -upnp -utils" 0 KiB
```

But no matter which version I build, I'll get the following error when I try to start the daemon:

```
Gridcoin: Error initializing database environment /home/babaei/.GridcoinResearch! To recover, BACKUP THAT DIRECTORY, then remove everything from it except for wallet.dat.
```

At first I thought maybe it's an issue with 3.7.12.0 or 3.7.13.0. But when I emerge 3.7.11.0 from your overly it gives the same error. When I revert back to my forked overlay with 3.7.11.0 it starts the server without giving that error. So, I'm sure that my database is fine.

I even tried doing what the error message said and deleted the whole directory and copied back my wallet and the config file. And it gives me the following error:

```
Gridcoin: wallet.dat corrupt, salvage failed
```

Again when I revert back to my own fork and start the server it won't throw this error too. So, I have no choice to go back to that fork and stick with 3.7.11.0 for now.

I believe there might be some misconfiguration at the build time that may causes the same error since my fork is an older version of yours that I manually modified up to 3.7.11.0 and I noticed you added some extra use flags.

Furthermore, I searched around for the same error and found a few similar errors with bitcoin and other altcoins and some suggested that might be an issue with berklydb version. Sorry I'm not an expert on this.

**Comment by NuLL3rr0r** [comment]
BTW, here is [the fork](https://github.com/NuLL3rr0r/gridcoin).

**Comment by nethershaw** [comment]
Prior to commit e82ac143fcc3285cb239465942b2986ad8ee6727, all ebuilds contained a bug:

```
Previous releases of these ebuilds would opportunistically build and
link against the highest version of sys-libs/db available. This could
resolve to BDB 6.0, which limits the portability of the wallet's
blockchain database files to other systems.

Additionally, the BDB_LIB_SUFFIX build option was omitted, which could
lead to inconsistent linking against libraries newer than the headers
with which the wallet's executables were built.

This commit correctly updates all existing production ebuilds to build
and link consistently against sys-libs/db:5.3 as upstream intended.
```

Ebuilds since then throw a warning about rebuilding the gridcoin databases because BDB 6.0 is not backward compatible with BDB 5.3. The solution is to back up _everything_, make sure your wallet `privatekey` and `publickey` are stored in your gridcoinresearch.conf (this is how you avoid losing access to your balance), and rebuild all of the databases from scratch _including_ wallet.dat.

This is not an issue with the current ebuilds; it's an issue with the older ebuilds depending on a newer BDB than they ought to.

**Comment by NuLL3rr0r** [comment]
Thank you so much for the info. I'll try that.
